package com.zxh.accountmanage.mapper;

import com.zxh.accountmanage.model.settleManage.ReportFormInfo;
import com.zxh.accountmanage.model.settleManage.ReportFormInfoExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;
@Mapper
public interface ReportFormInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_report_forms_info
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    long countByExample(ReportFormInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_report_forms_info
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    int deleteByExample(ReportFormInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_report_forms_info
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    int insert(ReportFormInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_report_forms_info
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    int insertSelective(ReportFormInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_report_forms_info
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    List<ReportFormInfo> selectByExampleWithBLOBsWithRowbounds(ReportFormInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_report_forms_info
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    List<ReportFormInfo> selectByExampleWithBLOBs(ReportFormInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_report_forms_info
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    List<ReportFormInfo> selectByExampleWithRowbounds(ReportFormInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_report_forms_info
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    List<ReportFormInfo> selectByExample(ReportFormInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_report_forms_info
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    int updateByExampleSelective(@Param("record") ReportFormInfo record, @Param("example") ReportFormInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_report_forms_info
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") ReportFormInfo record, @Param("example") ReportFormInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_report_forms_info
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    int updateByExample(@Param("record") ReportFormInfo record, @Param("example") ReportFormInfoExample example);
}