package com.zxh.accountmanage.model.retailAnalysis;

public class UserTradeLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_trade_log.user_id
     *
     * @mbg.generated Sat Aug 08 11:26:47 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_trade_log.username
     *
     * @mbg.generated Sat Aug 08 11:26:47 CST 2020
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_trade_log.user_id
     *
     * @return the value of user_trade_log.user_id
     *
     * @mbg.generated Sat Aug 08 11:26:47 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_trade_log.user_id
     *
     * @param userId the value for user_trade_log.user_id
     *
     * @mbg.generated Sat Aug 08 11:26:47 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_trade_log.username
     *
     * @return the value of user_trade_log.username
     *
     * @mbg.generated Sat Aug 08 11:26:47 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_trade_log.username
     *
     * @param username the value for user_trade_log.username
     *
     * @mbg.generated Sat Aug 08 11:26:47 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }
}