package com.zxh.accountmanage.model.settleManage;

import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.orderid
     *
     * @mbg.generated Tue Aug 04 17:18:18 CST 2020
     */
    private Long orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.money
     *
     * @mbg.generated Tue Aug 04 17:18:18 CST 2020
     */
    private Double money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.logtime
     *
     * @mbg.generated Tue Aug 04 17:18:18 CST 2020
     */
    private Date logtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.orderid
     *
     * @return the value of order.orderid
     *
     * @mbg.generated Tue Aug 04 17:18:18 CST 2020
     */
    public Long getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.orderid
     *
     * @param orderid the value for order.orderid
     *
     * @mbg.generated Tue Aug 04 17:18:18 CST 2020
     */
    public void setOrderid(Long orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.money
     *
     * @return the value of order.money
     *
     * @mbg.generated Tue Aug 04 17:18:18 CST 2020
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.money
     *
     * @param money the value for order.money
     *
     * @mbg.generated Tue Aug 04 17:18:18 CST 2020
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.logtime
     *
     * @return the value of order.logtime
     *
     * @mbg.generated Tue Aug 04 17:18:18 CST 2020
     */
    public Date getLogtime() {
        return logtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.logtime
     *
     * @param logtime the value for order.logtime
     *
     * @mbg.generated Tue Aug 04 17:18:18 CST 2020
     */
    public void setLogtime(Date logtime) {
        this.logtime = logtime;
    }
}