package com.zxh.accountmanage.model.settleManage;

import java.util.Date;

public class ReportFormDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_report_form_detail.id
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_report_form_detail.format_name
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    private String formatName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_report_form_detail.begin_time
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    private Date beginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_report_form_detail.end_time
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_report_form_detail.format_type
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    private String formatType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_report_form_detail.create_user
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_report_form_detail.create_time
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_report_form_detail.op_type
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    private Integer opType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_report_form_detail.id
     *
     * @return the value of bus_report_form_detail.id
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_report_form_detail.id
     *
     * @param id the value for bus_report_form_detail.id
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_report_form_detail.format_name
     *
     * @return the value of bus_report_form_detail.format_name
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    public String getFormatName() {
        return formatName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_report_form_detail.format_name
     *
     * @param formatName the value for bus_report_form_detail.format_name
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    public void setFormatName(String formatName) {
        this.formatName = formatName == null ? null : formatName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_report_form_detail.begin_time
     *
     * @return the value of bus_report_form_detail.begin_time
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_report_form_detail.begin_time
     *
     * @param beginTime the value for bus_report_form_detail.begin_time
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_report_form_detail.end_time
     *
     * @return the value of bus_report_form_detail.end_time
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_report_form_detail.end_time
     *
     * @param endTime the value for bus_report_form_detail.end_time
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_report_form_detail.format_type
     *
     * @return the value of bus_report_form_detail.format_type
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    public String getFormatType() {
        return formatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_report_form_detail.format_type
     *
     * @param formatType the value for bus_report_form_detail.format_type
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    public void setFormatType(String formatType) {
        this.formatType = formatType == null ? null : formatType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_report_form_detail.create_user
     *
     * @return the value of bus_report_form_detail.create_user
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_report_form_detail.create_user
     *
     * @param createUser the value for bus_report_form_detail.create_user
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_report_form_detail.create_time
     *
     * @return the value of bus_report_form_detail.create_time
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_report_form_detail.create_time
     *
     * @param createTime the value for bus_report_form_detail.create_time
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_report_form_detail.op_type
     *
     * @return the value of bus_report_form_detail.op_type
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    public Integer getOpType() {
        return opType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_report_form_detail.op_type
     *
     * @param opType the value for bus_report_form_detail.op_type
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    public void setOpType(Integer opType) {
        this.opType = opType;
    }
}