package com.zxh.accountmanage.model.settleManage;

public class ReportFormInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_report_forms_info.form_id
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    private Long formId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_report_forms_info.form_tab_name
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    private String formTabName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_report_forms_info.form_name
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    private String formName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_report_forms_info.form_id
     *
     * @return the value of bus_report_forms_info.form_id
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    public Long getFormId() {
        return formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_report_forms_info.form_id
     *
     * @param formId the value for bus_report_forms_info.form_id
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    public void setFormId(Long formId) {
        this.formId = formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_report_forms_info.form_tab_name
     *
     * @return the value of bus_report_forms_info.form_tab_name
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    public String getFormTabName() {
        return formTabName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_report_forms_info.form_tab_name
     *
     * @param formTabName the value for bus_report_forms_info.form_tab_name
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    public void setFormTabName(String formTabName) {
        this.formTabName = formTabName == null ? null : formTabName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_report_forms_info.form_name
     *
     * @return the value of bus_report_forms_info.form_name
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    public String getFormName() {
        return formName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_report_forms_info.form_name
     *
     * @param formName the value for bus_report_forms_info.form_name
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    public void setFormName(String formName) {
        this.formName = formName == null ? null : formName.trim();
    }
}