package com.zxh.accountmanage.model.settleManage;

import java.util.ArrayList;
import java.util.List;

public class ReportFormInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bus_report_forms_info
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bus_report_forms_info
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bus_report_forms_info
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_report_forms_info
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    public ReportFormInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_report_forms_info
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_report_forms_info
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_report_forms_info
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_report_forms_info
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_report_forms_info
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_report_forms_info
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_report_forms_info
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_report_forms_info
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_report_forms_info
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_report_forms_info
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bus_report_forms_info
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFormIdIsNull() {
            addCriterion("form_id is null");
            return (Criteria) this;
        }

        public Criteria andFormIdIsNotNull() {
            addCriterion("form_id is not null");
            return (Criteria) this;
        }

        public Criteria andFormIdEqualTo(Long value) {
            addCriterion("form_id =", value, "formId");
            return (Criteria) this;
        }

        public Criteria andFormIdNotEqualTo(Long value) {
            addCriterion("form_id <>", value, "formId");
            return (Criteria) this;
        }

        public Criteria andFormIdGreaterThan(Long value) {
            addCriterion("form_id >", value, "formId");
            return (Criteria) this;
        }

        public Criteria andFormIdGreaterThanOrEqualTo(Long value) {
            addCriterion("form_id >=", value, "formId");
            return (Criteria) this;
        }

        public Criteria andFormIdLessThan(Long value) {
            addCriterion("form_id <", value, "formId");
            return (Criteria) this;
        }

        public Criteria andFormIdLessThanOrEqualTo(Long value) {
            addCriterion("form_id <=", value, "formId");
            return (Criteria) this;
        }

        public Criteria andFormIdIn(List<Long> values) {
            addCriterion("form_id in", values, "formId");
            return (Criteria) this;
        }

        public Criteria andFormIdNotIn(List<Long> values) {
            addCriterion("form_id not in", values, "formId");
            return (Criteria) this;
        }

        public Criteria andFormIdBetween(Long value1, Long value2) {
            addCriterion("form_id between", value1, value2, "formId");
            return (Criteria) this;
        }

        public Criteria andFormIdNotBetween(Long value1, Long value2) {
            addCriterion("form_id not between", value1, value2, "formId");
            return (Criteria) this;
        }

        public Criteria andFormTabNameIsNull() {
            addCriterion("form_tab_name is null");
            return (Criteria) this;
        }

        public Criteria andFormTabNameIsNotNull() {
            addCriterion("form_tab_name is not null");
            return (Criteria) this;
        }

        public Criteria andFormTabNameEqualTo(String value) {
            addCriterion("form_tab_name =", value, "formTabName");
            return (Criteria) this;
        }

        public Criteria andFormTabNameNotEqualTo(String value) {
            addCriterion("form_tab_name <>", value, "formTabName");
            return (Criteria) this;
        }

        public Criteria andFormTabNameGreaterThan(String value) {
            addCriterion("form_tab_name >", value, "formTabName");
            return (Criteria) this;
        }

        public Criteria andFormTabNameGreaterThanOrEqualTo(String value) {
            addCriterion("form_tab_name >=", value, "formTabName");
            return (Criteria) this;
        }

        public Criteria andFormTabNameLessThan(String value) {
            addCriterion("form_tab_name <", value, "formTabName");
            return (Criteria) this;
        }

        public Criteria andFormTabNameLessThanOrEqualTo(String value) {
            addCriterion("form_tab_name <=", value, "formTabName");
            return (Criteria) this;
        }

        public Criteria andFormTabNameLike(String value) {
            addCriterion("form_tab_name like", value, "formTabName");
            return (Criteria) this;
        }

        public Criteria andFormTabNameNotLike(String value) {
            addCriterion("form_tab_name not like", value, "formTabName");
            return (Criteria) this;
        }

        public Criteria andFormTabNameIn(List<String> values) {
            addCriterion("form_tab_name in", values, "formTabName");
            return (Criteria) this;
        }

        public Criteria andFormTabNameNotIn(List<String> values) {
            addCriterion("form_tab_name not in", values, "formTabName");
            return (Criteria) this;
        }

        public Criteria andFormTabNameBetween(String value1, String value2) {
            addCriterion("form_tab_name between", value1, value2, "formTabName");
            return (Criteria) this;
        }

        public Criteria andFormTabNameNotBetween(String value1, String value2) {
            addCriterion("form_tab_name not between", value1, value2, "formTabName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bus_report_forms_info
     *
     * @mbg.generated do_not_delete_during_merge Sat Aug 08 08:59:07 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bus_report_forms_info
     *
     * @mbg.generated Sat Aug 08 08:59:07 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}