package com.zxh.accountmanage.model.settleManage;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SettleOrderInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bus_settle_order_info
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bus_settle_order_info
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bus_settle_order_info
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_settle_order_info
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    public SettleOrderInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_settle_order_info
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_settle_order_info
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_settle_order_info
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_settle_order_info
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_settle_order_info
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_settle_order_info
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_settle_order_info
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_settle_order_info
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_settle_order_info
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_settle_order_info
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bus_settle_order_info
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(Long value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(Long value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(Long value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(Long value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(Long value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(Long value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<Long> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<Long> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(Long value1, Long value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(Long value1, Long value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUsersIsNull() {
            addCriterion("users is null");
            return (Criteria) this;
        }

        public Criteria andUsersIsNotNull() {
            addCriterion("users is not null");
            return (Criteria) this;
        }

        public Criteria andUsersEqualTo(String value) {
            addCriterion("users =", value, "users");
            return (Criteria) this;
        }

        public Criteria andUsersNotEqualTo(String value) {
            addCriterion("users <>", value, "users");
            return (Criteria) this;
        }

        public Criteria andUsersGreaterThan(String value) {
            addCriterion("users >", value, "users");
            return (Criteria) this;
        }

        public Criteria andUsersGreaterThanOrEqualTo(String value) {
            addCriterion("users >=", value, "users");
            return (Criteria) this;
        }

        public Criteria andUsersLessThan(String value) {
            addCriterion("users <", value, "users");
            return (Criteria) this;
        }

        public Criteria andUsersLessThanOrEqualTo(String value) {
            addCriterion("users <=", value, "users");
            return (Criteria) this;
        }

        public Criteria andUsersLike(String value) {
            addCriterion("users like", value, "users");
            return (Criteria) this;
        }

        public Criteria andUsersNotLike(String value) {
            addCriterion("users not like", value, "users");
            return (Criteria) this;
        }

        public Criteria andUsersIn(List<String> values) {
            addCriterion("users in", values, "users");
            return (Criteria) this;
        }

        public Criteria andUsersNotIn(List<String> values) {
            addCriterion("users not in", values, "users");
            return (Criteria) this;
        }

        public Criteria andUsersBetween(String value1, String value2) {
            addCriterion("users between", value1, value2, "users");
            return (Criteria) this;
        }

        public Criteria andUsersNotBetween(String value1, String value2) {
            addCriterion("users not between", value1, value2, "users");
            return (Criteria) this;
        }

        public Criteria andRealUseIsNull() {
            addCriterion("real_use is null");
            return (Criteria) this;
        }

        public Criteria andRealUseIsNotNull() {
            addCriterion("real_use is not null");
            return (Criteria) this;
        }

        public Criteria andRealUseEqualTo(Double value) {
            addCriterion("real_use =", value, "realUse");
            return (Criteria) this;
        }

        public Criteria andRealUseNotEqualTo(Double value) {
            addCriterion("real_use <>", value, "realUse");
            return (Criteria) this;
        }

        public Criteria andRealUseGreaterThan(Double value) {
            addCriterion("real_use >", value, "realUse");
            return (Criteria) this;
        }

        public Criteria andRealUseGreaterThanOrEqualTo(Double value) {
            addCriterion("real_use >=", value, "realUse");
            return (Criteria) this;
        }

        public Criteria andRealUseLessThan(Double value) {
            addCriterion("real_use <", value, "realUse");
            return (Criteria) this;
        }

        public Criteria andRealUseLessThanOrEqualTo(Double value) {
            addCriterion("real_use <=", value, "realUse");
            return (Criteria) this;
        }

        public Criteria andRealUseIn(List<Double> values) {
            addCriterion("real_use in", values, "realUse");
            return (Criteria) this;
        }

        public Criteria andRealUseNotIn(List<Double> values) {
            addCriterion("real_use not in", values, "realUse");
            return (Criteria) this;
        }

        public Criteria andRealUseBetween(Double value1, Double value2) {
            addCriterion("real_use between", value1, value2, "realUse");
            return (Criteria) this;
        }

        public Criteria andRealUseNotBetween(Double value1, Double value2) {
            addCriterion("real_use not between", value1, value2, "realUse");
            return (Criteria) this;
        }

        public Criteria andPackageStatusIsNull() {
            addCriterion("package_status is null");
            return (Criteria) this;
        }

        public Criteria andPackageStatusIsNotNull() {
            addCriterion("package_status is not null");
            return (Criteria) this;
        }

        public Criteria andPackageStatusEqualTo(Integer value) {
            addCriterion("package_status =", value, "packageStatus");
            return (Criteria) this;
        }

        public Criteria andPackageStatusNotEqualTo(Integer value) {
            addCriterion("package_status <>", value, "packageStatus");
            return (Criteria) this;
        }

        public Criteria andPackageStatusGreaterThan(Integer value) {
            addCriterion("package_status >", value, "packageStatus");
            return (Criteria) this;
        }

        public Criteria andPackageStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("package_status >=", value, "packageStatus");
            return (Criteria) this;
        }

        public Criteria andPackageStatusLessThan(Integer value) {
            addCriterion("package_status <", value, "packageStatus");
            return (Criteria) this;
        }

        public Criteria andPackageStatusLessThanOrEqualTo(Integer value) {
            addCriterion("package_status <=", value, "packageStatus");
            return (Criteria) this;
        }

        public Criteria andPackageStatusIn(List<Integer> values) {
            addCriterion("package_status in", values, "packageStatus");
            return (Criteria) this;
        }

        public Criteria andPackageStatusNotIn(List<Integer> values) {
            addCriterion("package_status not in", values, "packageStatus");
            return (Criteria) this;
        }

        public Criteria andPackageStatusBetween(Integer value1, Integer value2) {
            addCriterion("package_status between", value1, value2, "packageStatus");
            return (Criteria) this;
        }

        public Criteria andPackageStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("package_status not between", value1, value2, "packageStatus");
            return (Criteria) this;
        }

        public Criteria andInspectStatusIsNull() {
            addCriterion("inspect_status is null");
            return (Criteria) this;
        }

        public Criteria andInspectStatusIsNotNull() {
            addCriterion("inspect_status is not null");
            return (Criteria) this;
        }

        public Criteria andInspectStatusEqualTo(Integer value) {
            addCriterion("inspect_status =", value, "inspectStatus");
            return (Criteria) this;
        }

        public Criteria andInspectStatusNotEqualTo(Integer value) {
            addCriterion("inspect_status <>", value, "inspectStatus");
            return (Criteria) this;
        }

        public Criteria andInspectStatusGreaterThan(Integer value) {
            addCriterion("inspect_status >", value, "inspectStatus");
            return (Criteria) this;
        }

        public Criteria andInspectStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("inspect_status >=", value, "inspectStatus");
            return (Criteria) this;
        }

        public Criteria andInspectStatusLessThan(Integer value) {
            addCriterion("inspect_status <", value, "inspectStatus");
            return (Criteria) this;
        }

        public Criteria andInspectStatusLessThanOrEqualTo(Integer value) {
            addCriterion("inspect_status <=", value, "inspectStatus");
            return (Criteria) this;
        }

        public Criteria andInspectStatusIn(List<Integer> values) {
            addCriterion("inspect_status in", values, "inspectStatus");
            return (Criteria) this;
        }

        public Criteria andInspectStatusNotIn(List<Integer> values) {
            addCriterion("inspect_status not in", values, "inspectStatus");
            return (Criteria) this;
        }

        public Criteria andInspectStatusBetween(Integer value1, Integer value2) {
            addCriterion("inspect_status between", value1, value2, "inspectStatus");
            return (Criteria) this;
        }

        public Criteria andInspectStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("inspect_status not between", value1, value2, "inspectStatus");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andOpTypeIsNull() {
            addCriterion("op_type is null");
            return (Criteria) this;
        }

        public Criteria andOpTypeIsNotNull() {
            addCriterion("op_type is not null");
            return (Criteria) this;
        }

        public Criteria andOpTypeEqualTo(Integer value) {
            addCriterion("op_type =", value, "opType");
            return (Criteria) this;
        }

        public Criteria andOpTypeNotEqualTo(Integer value) {
            addCriterion("op_type <>", value, "opType");
            return (Criteria) this;
        }

        public Criteria andOpTypeGreaterThan(Integer value) {
            addCriterion("op_type >", value, "opType");
            return (Criteria) this;
        }

        public Criteria andOpTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("op_type >=", value, "opType");
            return (Criteria) this;
        }

        public Criteria andOpTypeLessThan(Integer value) {
            addCriterion("op_type <", value, "opType");
            return (Criteria) this;
        }

        public Criteria andOpTypeLessThanOrEqualTo(Integer value) {
            addCriterion("op_type <=", value, "opType");
            return (Criteria) this;
        }

        public Criteria andOpTypeIn(List<Integer> values) {
            addCriterion("op_type in", values, "opType");
            return (Criteria) this;
        }

        public Criteria andOpTypeNotIn(List<Integer> values) {
            addCriterion("op_type not in", values, "opType");
            return (Criteria) this;
        }

        public Criteria andOpTypeBetween(Integer value1, Integer value2) {
            addCriterion("op_type between", value1, value2, "opType");
            return (Criteria) this;
        }

        public Criteria andOpTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("op_type not between", value1, value2, "opType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bus_settle_order_info
     *
     * @mbg.generated do_not_delete_during_merge Sat Aug 08 11:25:33 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bus_settle_order_info
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}