package com.zxh.accountmanage.model.settleManage;

import java.util.Date;

public class WholeSaleUserAccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_wholesale_useraccount.id
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_wholesale_useraccount.electric_charge
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    private Double electricCharge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_wholesale_useraccount.deviate_charge
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    private Double deviateCharge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_wholesale_useraccount.term_gap_charge
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    private Double termGapCharge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_wholesale_useraccount.term_settle_charge
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    private Double termSettleCharge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_wholesale_useraccount.share_charge
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    private Double shareCharge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_wholesale_useraccount.market_return_charge
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    private Double marketReturnCharge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_wholesale_useraccount.create_time
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_wholesale_useraccount.modify_time
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_wholesale_useraccount.id
     *
     * @return the value of bus_wholesale_useraccount.id
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_wholesale_useraccount.id
     *
     * @param id the value for bus_wholesale_useraccount.id
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_wholesale_useraccount.electric_charge
     *
     * @return the value of bus_wholesale_useraccount.electric_charge
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    public Double getElectricCharge() {
        return electricCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_wholesale_useraccount.electric_charge
     *
     * @param electricCharge the value for bus_wholesale_useraccount.electric_charge
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    public void setElectricCharge(Double electricCharge) {
        this.electricCharge = electricCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_wholesale_useraccount.deviate_charge
     *
     * @return the value of bus_wholesale_useraccount.deviate_charge
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    public Double getDeviateCharge() {
        return deviateCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_wholesale_useraccount.deviate_charge
     *
     * @param deviateCharge the value for bus_wholesale_useraccount.deviate_charge
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    public void setDeviateCharge(Double deviateCharge) {
        this.deviateCharge = deviateCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_wholesale_useraccount.term_gap_charge
     *
     * @return the value of bus_wholesale_useraccount.term_gap_charge
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    public Double getTermGapCharge() {
        return termGapCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_wholesale_useraccount.term_gap_charge
     *
     * @param termGapCharge the value for bus_wholesale_useraccount.term_gap_charge
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    public void setTermGapCharge(Double termGapCharge) {
        this.termGapCharge = termGapCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_wholesale_useraccount.term_settle_charge
     *
     * @return the value of bus_wholesale_useraccount.term_settle_charge
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    public Double getTermSettleCharge() {
        return termSettleCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_wholesale_useraccount.term_settle_charge
     *
     * @param termSettleCharge the value for bus_wholesale_useraccount.term_settle_charge
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    public void setTermSettleCharge(Double termSettleCharge) {
        this.termSettleCharge = termSettleCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_wholesale_useraccount.share_charge
     *
     * @return the value of bus_wholesale_useraccount.share_charge
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    public Double getShareCharge() {
        return shareCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_wholesale_useraccount.share_charge
     *
     * @param shareCharge the value for bus_wholesale_useraccount.share_charge
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    public void setShareCharge(Double shareCharge) {
        this.shareCharge = shareCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_wholesale_useraccount.market_return_charge
     *
     * @return the value of bus_wholesale_useraccount.market_return_charge
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    public Double getMarketReturnCharge() {
        return marketReturnCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_wholesale_useraccount.market_return_charge
     *
     * @param marketReturnCharge the value for bus_wholesale_useraccount.market_return_charge
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    public void setMarketReturnCharge(Double marketReturnCharge) {
        this.marketReturnCharge = marketReturnCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_wholesale_useraccount.create_time
     *
     * @return the value of bus_wholesale_useraccount.create_time
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_wholesale_useraccount.create_time
     *
     * @param createTime the value for bus_wholesale_useraccount.create_time
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_wholesale_useraccount.modify_time
     *
     * @return the value of bus_wholesale_useraccount.modify_time
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_wholesale_useraccount.modify_time
     *
     * @param modifyTime the value for bus_wholesale_useraccount.modify_time
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}