package com.zxh.accountmanage.mapper.settleManage;

import com.zxh.accountmanage.model.settleManage.OperateContract;
import com.zxh.accountmanage.model.settleManage.OperateContractExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OperateContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_operate_contract
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    long countByExample(OperateContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_operate_contract
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    int deleteByExample(OperateContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_operate_contract
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    int insert(OperateContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_operate_contract
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    int insertSelective(OperateContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_operate_contract
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    List<OperateContract> selectByExampleWithRowbounds(OperateContractExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_operate_contract
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    List<OperateContract> selectByExample(OperateContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_operate_contract
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    int updateByExampleSelective(@Param("record") OperateContract record, @Param("example") OperateContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_operate_contract
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    int updateByExample(@Param("record") OperateContract record, @Param("example") OperateContractExample example);
}