package com.zxh.accountmanage.mapper.settleManage;

import com.zxh.accountmanage.model.settleManage.ReportFormDetail;
import com.zxh.accountmanage.model.settleManage.ReportFormDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ReportFormDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_report_form_detail
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    long countByExample(ReportFormDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_report_form_detail
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    int deleteByExample(ReportFormDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_report_form_detail
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    int insert(ReportFormDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_report_form_detail
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    int insertSelective(ReportFormDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_report_form_detail
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    List<ReportFormDetail> selectByExampleWithRowbounds(ReportFormDetailExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_report_form_detail
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    List<ReportFormDetail> selectByExample(ReportFormDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_report_form_detail
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    int updateByExampleSelective(@Param("record") ReportFormDetail record, @Param("example") ReportFormDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_report_form_detail
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    int updateByExample(@Param("record") ReportFormDetail record, @Param("example") ReportFormDetailExample example);
}