package com.zxh.accountmanage.mapper.settleManage;

import com.zxh.accountmanage.model.settleManage.WholeSaleUserAccount;
import com.zxh.accountmanage.model.settleManage.WholeSaleUserAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WholeSaleUserAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_wholesale_useraccount
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    long countByExample(WholeSaleUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_wholesale_useraccount
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    int deleteByExample(WholeSaleUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_wholesale_useraccount
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    int insert(WholeSaleUserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_wholesale_useraccount
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    int insertSelective(WholeSaleUserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_wholesale_useraccount
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    List<WholeSaleUserAccount> selectByExampleWithRowbounds(WholeSaleUserAccountExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_wholesale_useraccount
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    List<WholeSaleUserAccount> selectByExample(WholeSaleUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_wholesale_useraccount
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    int updateByExampleSelective(@Param("record") WholeSaleUserAccount record, @Param("example") WholeSaleUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_wholesale_useraccount
     *
     * @mbg.generated Sat Aug 08 11:25:33 CST 2020
     */
    int updateByExample(@Param("record") WholeSaleUserAccount record, @Param("example") WholeSaleUserAccountExample example);
}